version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    volumes:
      - "./app/backend:/app/backend"
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    volumes:
      - "./app/frontend:/app/frontend"
