components:
- name: ElasticsearchDocumentStore
  params: {}
  type: ElasticsearchDocumentStore
- name: BM25Retriever
  params:
    document_store: ElasticsearchDocumentStore
  type: BM25Retriever
- name: PromptNode
  params:
    api_key: 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
    default_prompt_template: question-answering-per-document
    model_name_or_path: text-davinci-003
    max_length: 150
  type: PromptNode
pipelines:
- name: query
  nodes:
  - inputs:
    - Query
    name: BM25Retriever
  - inputs:
    - BM25Retriever
    name: PromptNode
version: 1.15.0
